const String BASE_URL = "https://staging-nilp.inroad.in/nadmin/"; //stagging
//const String BASE_URL = "http://3.94.34.119:8056/"; //ip
//const String BASE_URL = "http://192.168.0.172:8056/"; //test
//const String BASE_URL = "https://nilp.education.gov.in/nadmin/api/v1/"; //production
//const String BASE_URL = "https://nilp.education.gov.in/nadmin/"; //gov.in
const String BASE_URL_V1 = "https://staging-nilp.inroad.in:8056/api/v1/";
const String GET_MEMBER_DETAILS = "user/member/list/";
const String GET_EDITMEMBER_LIST = "user/member/editvt/";
const String GET_VT = "user/vt/list/";
const String GET_Edit_VT_List = "user/vtlist/editvt/";
const String VT_TAGGING = "user/vt/tagging/";
const String LEARNER = "8ca80f73-afd2-4d3f-b41d-e5bea0254b98";
const String VT = "8ecf3868-03b7-4ea1-8520-e619d793ed7d";
const String Check_Version_TYPE = "custom/list/getAppVersion/appVersion";
const String GET_OTP_EDIT_PROFILE = "user/request_email_mobile_otp/";
const String VERIFY_OTP_EDIT_PROFILE = "user/update_email_mobile/";
const String GET_SURVEY_TYPE = "api/list/getSurveyType/surveyType";
const String GENERATE_OTP = "user/surveyor/generate_otp";
const String OTP_LOGIN = "user/auth/otplogin";
const String DROPDOWN_VALUE = "master/data/mobile";
const String DASHBORAD_DATA = "user/dashboard/literacy_counter";
const String ADD_MEMBER = "user/member/add";
const String MULTIPLE_MEMBER = "user/member/multipleadd";
const String REFRESH_TOKEN = "auth/refresh";
const String MEMBER_UPDATE = "user/member/update";
const String Version_Api = "user/app/version";

const String RESEND_OTP = "user/auth/resend_otp";
const String VERSION = "custom/master/version";
const String HINDI_INSTRUCTION = BASE_URL + "survey/#/instruction/hi/0";
const String ASM_INSTRUCTION = BASE_URL + "survey/#/instruction/asm/0";
const String GUJ_INSTRUCTION = BASE_URL + "survey/#/instruction/guj/0";
const String PAN_INSTRUCTION = BASE_URL + "survey/#/instruction/pan/0";
const String KAN_INSTRUCTION = BASE_URL + "survey/#/instruction/kan/0";
const String MAR_INSTRUCTION = BASE_URL + "survey/#/instruction/mar/0";
const String MAL_INSTRUCTION = BASE_URL + "survey/#/instruction/mal/0";
const String TEL_INSTRUCTION = BASE_URL + "survey/#/instruction/tel/0";
const String ENGLISH_INSTRUCTION = BASE_URL + "survey/#/instruction/en/0";
