name: survey_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.6+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2
  platform: ^3.1.0
  package_info_plus: ^1.4.2
  launch_review: ^3.0.1
  shared_preferences: ^2.0.6
  dropdown_search: ^0.6.3
  google_fonts: ^2.1.0
  easy_localization: ^3.0.0
  fluttertoast: ^8.0.8
  http: ^0.13.0
  encrypt: ^5.0.1
  provider: ^6.0.0
  pointycastle: ^3.3.4
  cryptography: ^2.0.2
  tuple: ^2.0.0
  encryptions: ^1.0.0
  cached_network_image: ^3.1.0
  flutter_svg: ^0.21.0
  data_connection_checker: ^0.3.4
  connectivity_plus: ^2.0.2
  pin_code_fields: ^7.3.0
  flutter_inappwebview: ^5.3.2



dev_dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/
    - images/sendsurvey.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Black.ttf
        - asset: fonts/Poppins-BlackItalic.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-BoldItalic.ttf
        - asset: fonts/Poppins-Italic.ttf
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-LightItalic.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-MediumItalic.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Thin.ttf
        - asset: fonts/Poppins-ThinItalic.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf


